name: Setup build.yml

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Resource Packs
        run: "for dir in */; do zip -r \"./${dir%/}.zip\" \"$dir\"; done"

      - name: Create Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          title: Build ${{ github.run_number }}
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: "v${{ github.run_number }}"
          files: "*.zip"
